Remove upper version constraint on hashicorp/random
traveloka/terraform-aws-iam-role pull request #52
Opened 2022-04-05 16:48 UTC by slinkdarga

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

***

Fixes #51

2022-05-06 07:02 UTC, salvianreynaldi commented
+1 this,
probably there's still a value in retaining the upper limit, e.g. to version `3.x`, as 4.x might break things

2022-05-24 06:48 UTC, salvianreynaldi commented
v3.0.0's breaking change is only [the removal of the `b64` attribute](https://github.com/hashicorp/terraform-provider-random/commit/486d27e8730b6f3a6dc9cec27aebbea8596f3422), which is not used in this repo, so it should be safe to use.

@slinkdarga could you update the PR to add 3.x as the (inclusive) upper limit as above?

2022-05-24 07:08 UTC, vincenttjia requested changes

2022-05-24 07:08 UTC, vincenttjia commented on modules/crossaccount/versions.tf
> -      version = ">= 1.2.0, < 3.0.0"
Please add an upper version limit

```
version = ">= 1.2.0, < 4.0.0"
```

2022-05-24 07:08 UTC, vincenttjia commented on modules/external/versions.tf
> -      version = ">= 1.0.0, < 3.0.0"
Please add an upper version limit

```
version = ">= 1.2.0, < 4.0.0"
```

2022-05-24 07:08 UTC, vincenttjia commented on modules/instance/versions.tf
> -      version = ">= 1.2.0, < 3.0.0"
Please add an upper version limit

```
version = ">= 1.2.0, < 4.0.0"
```

2022-05-24 07:08 UTC, vincenttjia commented on modules/lambda/versions.tf
> -      version = ">= 1.2.0, < 3.0.0"
Please add an upper version limit

```
version = ">= 1.2.0, < 4.0.0"
```

2022-05-24 07:08 UTC, vincenttjia commented on modules/service/versions.tf
> -      version = ">= 1.2.0, < 3.0.0"
Please add an upper version limit

```
version = ">= 1.2.0, < 4.0.0"
```

2022-05-27 06:25 UTC, salvianreynaldi commented
Hi @vincenttjia,
I've updated the line, kindly review 🙇

2022-05-30 03:37 UTC, vincenttjia approved these changes
LGTM

2022-05-30 04:00 UTC, vincenttjia submitted a review, later dismissed

2022-05-30 07:34 UTC, merged